# Generated by Django 4.0 on 2021-12-14 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=250, verbose_name='Make')),
                ('model', models.CharField(max_length=250, verbose_name='Model')),
                ('plate_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\s\\d{4}\\s[A-Z]{2}$')], verbose_name='Plate_number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'vehicle',
                'db_table': 'vehicles',
            },
        ),
    ]
